In [1]:
import numpy as np

In [6]:
my_list = list(range(0,10))
type(my_list)

list

In [7]:
np.array(my_list)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(low=10, size=(3, 4, 5))  # Three-dimensional array

print(f"x1 = {x1} \nx2 = {x2} \nx3 = {x3}")

x1 = [0 7 2 9 2 5] 
x2 = [[8 0 4 0]
 [7 4 4 0]
 [8 0 4 2]] 
x3 = [[[1 9 3 1 1]
  [3 9 2 3 1]
  [7 9 5 4 7]
  [4 5 9 5 2]]

 [[9 9 5 2 2]
  [2 9 7 3 1]
  [2 3 4 3 0]
  [8 1 4 5 1]]

 [[3 6 5 5 5]
  [5 1 7 6 7]
  [3 9 7 7 2]
  [4 4 0 6 8]]]


In [7]:
# rang is form start to end - 1  
c = np.arange(0,10) 
len(c)

[0 1 2 3 4 5 6 7 8 9]


dtype('int32')

In [13]:
np.random.randn(2, 4)

array([[ 0.10894268, -0.14118702, -1.00811038,  0.13049913],
       [ 0.61210562, -0.10697807, -1.40812731,  1.54872422]])

In [14]:
np.random.rand(2, 4)

array([[0.48228888, 0.1685875 , 0.4714683 , 0.34030273],
       [0.71902831, 0.23144241, 0.38221097, 0.03481661]])

In [6]:
arr = np.arange(0, 20, dtype=int)

print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [9]:
print(arr.reshape(4,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [12]:
print(arr.reshape(5, 4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
